/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2022-07-20 07:25:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1658301680000L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1658301912000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("プログラム名:menu.jsp\r\n");
      out.write("プログラムの説明:メニュー画面を表示するプログラム\r\n");
      out.write("作成者:櫻井 康稀\r\n");
      out.write("作成日:2022/7/20\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>管理メニュー画面</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"container-fuild\">\r\n");
      out.write("\t<div class=\"header-wrapper\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<header class=\"mb-5 justify-content-center\">\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"admin-nav navbar navbar-expand-sm border-bottom border-warning border-3 py-3\">\r\n");
      out.write("\t\t<a class=\"navbar-brand \" href=\"menu.html\"> <img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print( request.getContextPath() );
      out.write("/img/logo.png\" class=\"ms-5\"\r\n");
      out.write("\t\t\talt=\"logo\" height=\"50px\" width=\"200px\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"position-center\">\r\n");
      out.write("\t\t\t<p class=\"fs-1 fw-bolder\">NEMU</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"body-wrapper text-center container\">\r\n");
      out.write("\t\t<div class=\"card-list row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"insert.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"http://illustrain.com/img/work/2016/illustrain10-sakka-06.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"商品登録\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">商品登録</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"list.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://www.illust-box.jp/db_img/sozai/00011/110903/watermark.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"ユニフォーム一覧\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">一覧</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"insertUser.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://msp.c.yimg.jp/images/v2/FUTi93tXq405grZVGgDqG0-wNvfK14_cc0t0Zx4f-nI6i71sVzAHbwmdy7LJV9eVV1d8RQRvUMmgy374Mp7H0uhOSE_Dq_LBcP8SMRbxul4XKhvHcxgag2DiDwCddlxeIIH4Xk91Wb0EF1JUqe16J4gbCegNCMfHXfDM4URTyuC9FhMZWYOhSF0mb3KkBwJwkAAksGKiLlvjd3mPc6J24Z5SjoC0IKgANtlNebsLxSoSyiEgCv0snmuf4LWsDjcs/kkrn_icon_user_2.png?errorImage=false\"\r\n");
      out.write("\t\t\t\t\t\talt=\"ユーザ登録\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">ユーザー登録</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listUser.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://msp.c.yimg.jp/images/v2/FUTi93tXq405grZVGgDqG1kFgzUBi2vigmURnXfA8ObhlKcr6bL83fHqUL_iyS_GXRiKu4DJgT_aKd9TFDRURafwJtqnmAclZwXE9mJxZQUX8AX3qh-9DSXgfibyHETgg2yuG7mNSq88XqMdvk2yXQS57kIupebaUn4ClHwNLIQISGFG1domNu1A3D5ZudQSoeV78UIubjFqGpPeblh-ZU3K3-HgLTqBYvsqLy_vPEo=/c7571a9645cb62517b77270e03d5e739_t.jpeg?errorImage=false\"\r\n");
      out.write("\t\t\t\t\t\talt=\"ユーザ一覧\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">ユーザ一覧</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"showSaleByMonth.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://msp.c.yimg.jp/images/v2/FUTi93tXq405grZVGgDqG7s6XIz6WzUM9mMsixYxaAusUx8TA0uLAHGqfYpuwWicPPu9FJd-qR0DUQNwSNtpeDL4PwuheJ-OdTjHJGQ5X3S4XwgQ9WNFl-tS6g8Ho-831U_A8MkNd8NJieJROdCxNkCdasaqd6QZhV22jNskGnglj9jmrWYgAndbQdZaTMhzehACo-Jaa5xMXPSUoRaV55JFtXD15YXTic1FKwp6VGCkCzVck3sfu5HZT0yOh0rSsE7os_uJ3piagqBM3ujSl69vvgHJN9kQCToCNctiYT9HNeSQL6dZDMfSvkzC_rEejw4HsBnYgW-xVF5WhzDkQv8lPkEMhx3gPtS5mXYhlghDSY8tPzwPAzLfL0jIhSILkwJ0D-CG4KeP884C-PFFqujY4ACAA-cCgfcNrCSAXXVvUdc_NCY56UW4lQk79OzikhYDoT2LC7_7CZOKij1T2ybOBi9DD1pBLcDIbOkBJu3fKIWolGYb5X3jazwQ9aUKNA54WQc-VJKmV6DfNKnmrQ==/bar-chart-and-red-arrow-vector-id1314976273?errorImage=false\"\r\n");
      out.write("\t\t\t\t\t\talt=\"売上状況\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">売上状況</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"showOrderedItem.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://msp.c.yimg.jp/images/v2/FUTi93tXq405grZVGgDqG1kFgzUBi2vigmURnXfA8OZu2TPe2bije0ESb3VVAq1GVec8YvKhxT30CASZvmDj_mi1mq6Uxa7uqSx-2q61KCwX8AX3qh-9DSXgfibyHETgg2yuG7mNSq88XqMdvk2yXQ0w-HmJ_HMuqs6LbkiaOxi9uDZKOV3pF-ZTjRyimwQMDKraqLOJP850HA0lvluBipspaIMJO6MOMBGtmFOEvqk=/8f780a84d203795f885139d3ccd30729_t.jpeg?errorImage=false\"\r\n");
      out.write("\t\t\t\t\t\talt=\"購入状況確認\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">購入状況</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 mb-5\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"login.html\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://msp.c.yimg.jp/images/v2/FUTi93tXq405grZVGgDqG1kFgzUBi2vigmURnXfA8OaWvDBf6amQT0k-8JjRRdFdworF2MQq4SEUXJIr6nZp_i840Mwi_xv6VN1aJpwnBZMX8AX3qh-9DSXgfibyHETgg2yuG7mNSq88XqMdvk2yXUJZmwElhHv8dsWNh8QzKvXOX91hfZKmVJYzPFlgma_JQJZaU_-JWAR6ggmCHvnIIZ-bVTk1aSdhjd4hM3FiBNA=/727a1d2c03191edfbf4c77e6ecb908b6_t.jpeg?errorImage=false\"\r\n");
      out.write("\t\t\t\t\t\talt=\"ログアウト\" height=\"150\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">ログアウト</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer-wrapper\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<footer class=\"fixed-bottom container\">\r\n");
      out.write("\t<div class=\"border-top border-warning border-3 p-3\">\r\n");
      out.write("\t\t<p>Copyright&copy; 2022 All Right Reserved.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
